name: Test a scheduled job
on:
  schedule:
    - cron: '*/5 * * * *'  # run every 5min
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo okay
