name: Test a scheduled job
on:
  #schedule:
  #  - cron: '*/5 * * * *'  # run every 5min
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - run: rustup update beta && rustup default beta
      - name: Compile the code with the beta compiler
        id: build-beta
        run: |
          set -uex
          if ! cargo run > error.log 2>&1; then
            printf 'Hello, I have detected, that this repository does not work with the current beta compiler.\n\nIt looks like, there were changes introduced, that broke this repository. The error was:\n```console\n%s\n```\nPlease take actions to fix this before the behavior reaches stable.' "$(< error.log)" | gh issue create --title 'The compilation fails with current beta compiler' --body-file -
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
