name: Test a scheduled job
on:
  schedule:
    - cron: '*/5 * * * *'  # run every 5min
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # https://docs.github.com/en/actions/use-cases-and-examples/project-management/scheduling-issue-creation
      - run: gh issue create --title "Test Issue created by periodic Workflow" --body "This was created on $(date)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}