name: Test a scheduled job
on:
  schedule:
    - cron: '*/5 * * * *'  # run every 5min
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - run: rustup update beta && rustup default beta
      - name: Compile the code with the beta compiler
        id: build-beta
        run: |
          set -uex
          if ! cargo run > error.log 2>&1; then
            echo "compiler-output=$(cat error.log)" >> $GITHUB_OUTPUT
            false
          fi
      # https://docs.github.com/en/actions/use-cases-and-examples/project-management/scheduling-issue-creation
      - name: Create an issue, since the beta-build is broken
        run: printf 'Hello, I have detected, that this repository does not work with the current beta compiler.\n\nIt looks like, there were changes introduced, that broke this repository. Please take actions to fix this before the behavior reaches stable. The error was:\n```console\n%s\n```' "${{steps.build-beta.outputs.compiler-output}}" | gh issue create --title 'The compilation fails with current beta compiler' --body-file -
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}